// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0--rc3
// source: artist_service.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FollowerCount int32  `protobuf:"varint,5,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Artist) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Artist) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type CreateArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bio  string `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
}

func (x *CreateArtistRequest) Reset() {
	*x = CreateArtistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtistRequest) ProtoMessage() {}

func (x *CreateArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtistRequest.ProtoReflect.Descriptor instead.
func (*CreateArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArtistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateArtistRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type CreateArtistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *CreateArtistResponse) Reset() {
	*x = CreateArtistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtistResponse) ProtoMessage() {}

func (x *CreateArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtistResponse.ProtoReflect.Descriptor instead.
func (*CreateArtistResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArtistResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type ReadArtistByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadArtistByIdRequest) Reset() {
	*x = ReadArtistByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistByIdRequest) ProtoMessage() {}

func (x *ReadArtistByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistByIdRequest.ProtoReflect.Descriptor instead.
func (*ReadArtistByIdRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadArtistByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadArtistByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *ReadArtistByIdResponse) Reset() {
	*x = ReadArtistByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistByIdResponse) ProtoMessage() {}

func (x *ReadArtistByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistByIdResponse.ProtoReflect.Descriptor instead.
func (*ReadArtistByIdResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadArtistByIdResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type ReadArtistByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReadArtistByNameRequest) Reset() {
	*x = ReadArtistByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistByNameRequest) ProtoMessage() {}

func (x *ReadArtistByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistByNameRequest.ProtoReflect.Descriptor instead.
func (*ReadArtistByNameRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadArtistByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadArtistByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *ReadArtistByNameResponse) Reset() {
	*x = ReadArtistByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistByNameResponse) ProtoMessage() {}

func (x *ReadArtistByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistByNameResponse.ProtoReflect.Descriptor instead.
func (*ReadArtistByNameResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadArtistByNameResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type ReadArtistBioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadArtistBioRequest) Reset() {
	*x = ReadArtistBioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistBioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistBioRequest) ProtoMessage() {}

func (x *ReadArtistBioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistBioRequest.ProtoReflect.Descriptor instead.
func (*ReadArtistBioRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadArtistBioRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadArtistBioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bio string `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
}

func (x *ReadArtistBioResponse) Reset() {
	*x = ReadArtistBioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistBioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistBioResponse) ProtoMessage() {}

func (x *ReadArtistBioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistBioResponse.ProtoReflect.Descriptor instead.
func (*ReadArtistBioResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadArtistBioResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type ReadArtistFollowerCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadArtistFollowerCountRequest) Reset() {
	*x = ReadArtistFollowerCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistFollowerCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistFollowerCountRequest) ProtoMessage() {}

func (x *ReadArtistFollowerCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistFollowerCountRequest.ProtoReflect.Descriptor instead.
func (*ReadArtistFollowerCountRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadArtistFollowerCountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadArtistFollowerCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowerCount int32 `protobuf:"varint,1,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
}

func (x *ReadArtistFollowerCountResponse) Reset() {
	*x = ReadArtistFollowerCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArtistFollowerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtistFollowerCountResponse) ProtoMessage() {}

func (x *ReadArtistFollowerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtistFollowerCountResponse.ProtoReflect.Descriptor instead.
func (*ReadArtistFollowerCountResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadArtistFollowerCountResponse) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type UpdateArtistNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateArtistNameRequest) Reset() {
	*x = UpdateArtistNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistNameRequest) ProtoMessage() {}

func (x *UpdateArtistNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtistNameRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateArtistNameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArtistNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateArtistNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *UpdateArtistNameResponse) Reset() {
	*x = UpdateArtistNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistNameResponse) ProtoMessage() {}

func (x *UpdateArtistNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateArtistNameResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateArtistNameResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type UpdateArtistBioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bio string `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
}

func (x *UpdateArtistBioRequest) Reset() {
	*x = UpdateArtistBioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistBioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistBioRequest) ProtoMessage() {}

func (x *UpdateArtistBioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistBioRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtistBioRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArtistBioRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArtistBioRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateArtistBioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *UpdateArtistBioResponse) Reset() {
	*x = UpdateArtistBioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistBioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistBioResponse) ProtoMessage() {}

func (x *UpdateArtistBioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistBioResponse.ProtoReflect.Descriptor instead.
func (*UpdateArtistBioResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateArtistBioResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type UpdateArtistFollowerCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowerCount int32 `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
}

func (x *UpdateArtistFollowerCountRequest) Reset() {
	*x = UpdateArtistFollowerCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistFollowerCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistFollowerCountRequest) ProtoMessage() {}

func (x *UpdateArtistFollowerCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistFollowerCountRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtistFollowerCountRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateArtistFollowerCountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArtistFollowerCountRequest) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type UpdateArtistFollowerCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *UpdateArtistFollowerCountResponse) Reset() {
	*x = UpdateArtistFollowerCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistFollowerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistFollowerCountResponse) ProtoMessage() {}

func (x *UpdateArtistFollowerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistFollowerCountResponse.ProtoReflect.Descriptor instead.
func (*UpdateArtistFollowerCountResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateArtistFollowerCountResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type DeleteArtistByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteArtistByIdRequest) Reset() {
	*x = DeleteArtistByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArtistByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistByIdRequest) ProtoMessage() {}

func (x *DeleteArtistByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtistByIdRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteArtistByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArtistByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *DeleteArtistByIdResponse) Reset() {
	*x = DeleteArtistByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArtistByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistByIdResponse) ProtoMessage() {}

func (x *DeleteArtistByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtistByIdResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteArtistByIdResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

type DeleteAllArtistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAllArtistsRequest) Reset() {
	*x = DeleteAllArtistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllArtistsRequest) ProtoMessage() {}

func (x *DeleteAllArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllArtistsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllArtistsRequest) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{19}
}

type DeleteAllArtistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAllArtistsResponse) Reset() {
	*x = DeleteAllArtistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artist_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllArtistsResponse) ProtoMessage() {}

func (x *DeleteAllArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllArtistsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllArtistsResponse) Descriptor() ([]byte, []int) {
	return file_artist_service_proto_rawDescGZIP(), []int{20}
}

var File_artist_service_proto protoreflect.FileDescriptor

var file_artist_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x70, 0x64, 0x62, 0x22, 0x84, 0x01, 0x0a,
	0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62,
	0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f,
	0x22, 0x3c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x27,
	0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52,
	0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x29, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x22, 0x30, 0x0a, 0x1e, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a,
	0x1f, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x62, 0x69, 0x6f, 0x22, 0x3f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x06, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x49, 0x0a, 0x21, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xfb, 0x06, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x47, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x19, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x70, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x6d,
	0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x70, 0x64, 0x62,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x2e,
	0x6d, 0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d,
	0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e,
	0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c,
	0x0a, 0x1b, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x24, 0x2e,
	0x6d, 0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x42, 0x69, 0x6f, 0x12, 0x1c, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x6e, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x26, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x70, 0x64, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x6d,
	0x70, 0x64, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x70,
	0x64, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x73, 0x68, 0x69,
	0x62, 0x6c, 0x69, 0x32, 0x30, 0x30, 0x32, 0x2f, 0x6d, 0x62, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_artist_service_proto_rawDescOnce sync.Once
	file_artist_service_proto_rawDescData = file_artist_service_proto_rawDesc
)

func file_artist_service_proto_rawDescGZIP() []byte {
	file_artist_service_proto_rawDescOnce.Do(func() {
		file_artist_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_artist_service_proto_rawDescData)
	})
	return file_artist_service_proto_rawDescData
}

var file_artist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_artist_service_proto_goTypes = []interface{}{
	(*Artist)(nil),                            // 0: mpdb.Artist
	(*CreateArtistRequest)(nil),               // 1: mpdb.CreateArtistRequest
	(*CreateArtistResponse)(nil),              // 2: mpdb.CreateArtistResponse
	(*ReadArtistByIdRequest)(nil),             // 3: mpdb.ReadArtistByIdRequest
	(*ReadArtistByIdResponse)(nil),            // 4: mpdb.ReadArtistByIdResponse
	(*ReadArtistByNameRequest)(nil),           // 5: mpdb.ReadArtistByNameRequest
	(*ReadArtistByNameResponse)(nil),          // 6: mpdb.ReadArtistByNameResponse
	(*ReadArtistBioRequest)(nil),              // 7: mpdb.ReadArtistBioRequest
	(*ReadArtistBioResponse)(nil),             // 8: mpdb.ReadArtistBioResponse
	(*ReadArtistFollowerCountRequest)(nil),    // 9: mpdb.ReadArtistFollowerCountRequest
	(*ReadArtistFollowerCountResponse)(nil),   // 10: mpdb.ReadArtistFollowerCountResponse
	(*UpdateArtistNameRequest)(nil),           // 11: mpdb.UpdateArtistNameRequest
	(*UpdateArtistNameResponse)(nil),          // 12: mpdb.UpdateArtistNameResponse
	(*UpdateArtistBioRequest)(nil),            // 13: mpdb.UpdateArtistBioRequest
	(*UpdateArtistBioResponse)(nil),           // 14: mpdb.UpdateArtistBioResponse
	(*UpdateArtistFollowerCountRequest)(nil),  // 15: mpdb.UpdateArtistFollowerCountRequest
	(*UpdateArtistFollowerCountResponse)(nil), // 16: mpdb.UpdateArtistFollowerCountResponse
	(*DeleteArtistByIdRequest)(nil),           // 17: mpdb.DeleteArtistByIdRequest
	(*DeleteArtistByIdResponse)(nil),          // 18: mpdb.DeleteArtistByIdResponse
	(*DeleteAllArtistsRequest)(nil),           // 19: mpdb.DeleteAllArtistsRequest
	(*DeleteAllArtistsResponse)(nil),          // 20: mpdb.DeleteAllArtistsResponse
}
var file_artist_service_proto_depIdxs = []int32{
	0,  // 0: mpdb.CreateArtistResponse.artist:type_name -> mpdb.Artist
	0,  // 1: mpdb.ReadArtistByIdResponse.artist:type_name -> mpdb.Artist
	0,  // 2: mpdb.ReadArtistByNameResponse.artist:type_name -> mpdb.Artist
	0,  // 3: mpdb.UpdateArtistNameResponse.artist:type_name -> mpdb.Artist
	0,  // 4: mpdb.UpdateArtistBioResponse.artist:type_name -> mpdb.Artist
	0,  // 5: mpdb.UpdateArtistFollowerCountResponse.artist:type_name -> mpdb.Artist
	0,  // 6: mpdb.DeleteArtistByIdResponse.artist:type_name -> mpdb.Artist
	1,  // 7: mpdb.ArtistService.CreateArtist:input_type -> mpdb.CreateArtistRequest
	3,  // 8: mpdb.ArtistService.ReadArtistById:input_type -> mpdb.ReadArtistByIdRequest
	5,  // 9: mpdb.ArtistService.ReadArtistByName:input_type -> mpdb.ReadArtistByNameRequest
	7,  // 10: mpdb.ArtistService.ReadArtistBioById:input_type -> mpdb.ReadArtistBioRequest
	9,  // 11: mpdb.ArtistService.ReadArtistFollowerCountById:input_type -> mpdb.ReadArtistFollowerCountRequest
	11, // 12: mpdb.ArtistService.UpdateArtistName:input_type -> mpdb.UpdateArtistNameRequest
	13, // 13: mpdb.ArtistService.UpdateArtistBio:input_type -> mpdb.UpdateArtistBioRequest
	15, // 14: mpdb.ArtistService.UpdateArtistFollowerCount:input_type -> mpdb.UpdateArtistFollowerCountRequest
	17, // 15: mpdb.ArtistService.DeleteArtistById:input_type -> mpdb.DeleteArtistByIdRequest
	19, // 16: mpdb.ArtistService.DeleteAllArtists:input_type -> mpdb.DeleteAllArtistsRequest
	2,  // 17: mpdb.ArtistService.CreateArtist:output_type -> mpdb.CreateArtistResponse
	4,  // 18: mpdb.ArtistService.ReadArtistById:output_type -> mpdb.ReadArtistByIdResponse
	6,  // 19: mpdb.ArtistService.ReadArtistByName:output_type -> mpdb.ReadArtistByNameResponse
	8,  // 20: mpdb.ArtistService.ReadArtistBioById:output_type -> mpdb.ReadArtistBioResponse
	10, // 21: mpdb.ArtistService.ReadArtistFollowerCountById:output_type -> mpdb.ReadArtistFollowerCountResponse
	12, // 22: mpdb.ArtistService.UpdateArtistName:output_type -> mpdb.UpdateArtistNameResponse
	14, // 23: mpdb.ArtistService.UpdateArtistBio:output_type -> mpdb.UpdateArtistBioResponse
	16, // 24: mpdb.ArtistService.UpdateArtistFollowerCount:output_type -> mpdb.UpdateArtistFollowerCountResponse
	18, // 25: mpdb.ArtistService.DeleteArtistById:output_type -> mpdb.DeleteArtistByIdResponse
	20, // 26: mpdb.ArtistService.DeleteAllArtists:output_type -> mpdb.DeleteAllArtistsResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_artist_service_proto_init() }
func file_artist_service_proto_init() {
	if File_artist_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_artist_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArtistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArtistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistBioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistBioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistFollowerCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArtistFollowerCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistBioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistBioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistFollowerCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistFollowerCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteArtistByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteArtistByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllArtistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artist_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllArtistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artist_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artist_service_proto_goTypes,
		DependencyIndexes: file_artist_service_proto_depIdxs,
		MessageInfos:      file_artist_service_proto_msgTypes,
	}.Build()
	File_artist_service_proto = out.File
	file_artist_service_proto_rawDesc = nil
	file_artist_service_proto_goTypes = nil
	file_artist_service_proto_depIdxs = nil
}
